jobs:
  - name: retrieve-secrets-job
    plan:
      - task: retrieve-secrets
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: concourse-1
          run:
            path: bash
            args:
              - -c
              - |
                #!/bin/bash
 
                # Login to Vault using username and password
                vault login -method=userpass username=vaishnavi password=vaishnavi
 
                # Retrieve the secrets from Vault
                username=$(vault kv get -field=username mysecrets/path)
                password=$(vault kv get -field=password mysecrets/path)
 
                # Print the retrieved secrets to the log
                echo "Retrieved Username: $username"
                echo "Retrieved Password: $password"